plugin:
    name: 'dilexus.octobase::lang.plugin.name'
    description: 'dilexus.octobase::lang.plugin.description'
    author: Dilexus
    icon: oc-icon-server
    homepage: ''
permissions:
    dilexus.octobase.manage:
        tab: Octobase
        label: 'Manage Octobase'
